spring:
    banner:
        location: classpath:banner.txt
    h2:
        console:
            enabled: true
            path: /database/h2
    datasource:
        url: jdbc:h2:mem:db;
        username: dbuser
        password:
        driver-class-name: org.h2.Driver
    sql:
        init:
            mode: embedded
            data-locations:
                - classpath*:db/${spring.jpa.database}/data.sql
    jpa:
        database: h2
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: update
        # show-sql: true
    output:
        ansi:
            enabled: always
